// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nq12TutH13we1UigJmjqSV
// Component: sScL-67mZ4
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Title from "../../Title"; // plasmic-import: vrVBAkZgK6/component
import ResumeBlock from "../../ResumeBlock"; // plasmic-import: Bnf8zBpPgU/component
import TagStack from "../../TagStack"; // plasmic-import: ftq3RaS44j/component
import ResumeTag from "../../ResumeTag"; // plasmic-import: zTvZ3EPO88/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_tag_resume.module.css"; // plasmic-import: nq12TutH13we1UigJmjqSV/projectcss
import sty from "./PlasmicResumeHeading.module.css"; // plasmic-import: sScL-67mZ4/css

export const PlasmicResumeHeading__VariantProps = new Array();

export const PlasmicResumeHeading__ArgProps = new Array();

function PlasmicResumeHeading__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Title
        data-plasmic-name={"title"}
        data-plasmic-override={overrides.title}
        className={classNames("__wab_instance", sty.title)}
        heading={true}
        text={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__at66A
            )}
          >
            {"heading title"}
          </div>
        }
      />

      <div
        data-plasmic-name={"blocks"}
        data-plasmic-override={overrides.blocks}
        className={classNames(projectcss.all, sty.blocks)}
      >
        <ResumeBlock
          blockNumber={"1"}
          className={classNames("__wab_instance", sty.resumeBlock___0CKDu)}
          tagStackTarget={
            <TagStack
              className={classNames("__wab_instance", sty.tagStack__eovT)}
            >
              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__ejVeL)}
                tagContent={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rjH3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jvkmS
                      )}
                    >
                      {"html"}
                    </div>
                  </div>
                }
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__ijZdG)}
                tagContent={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__u0Ulo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ruMrR
                      )}
                    >
                      {"css"}
                    </div>
                  </div>
                }
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__mTc)}
                tagContent={
                  <div
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    className={classNames(projectcss.all, sty.freeBox)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wo2Pk
                      )}
                    >
                      {"tag 1"}
                    </div>
                  </div>
                }
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__biReq)}
                tagContent={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xz1Bm)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lw9Pc
                      )}
                    >
                      {"javascript"}
                    </div>
                  </div>
                }
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__swAqb)}
                tagContent={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nYfir)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eqAbc
                      )}
                    >
                      {"websockets"}
                    </div>
                  </div>
                }
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__dXsJm)}
                tagContent={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qrFoy)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___41GSg
                      )}
                    >
                      {"react"}
                    </div>
                  </div>
                }
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__a4Gri)}
              />
            </TagStack>
          }
        />

        <ResumeBlock
          blockNumber={"1"}
          className={classNames("__wab_instance", sty.resumeBlock__hALv)}
          tagStackTarget={
            <TagStack
              className={classNames("__wab_instance", sty.tagStack__uW9Kb)}
            >
              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__sUctb)}
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__ijZdG)}
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__mTc)}
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__biReq)}
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__swAqb)}
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__dXsJm)}
              />

              <ResumeTag
                className={classNames("__wab_instance", sty.resumeTag__a4Gri)}
              />
            </TagStack>
          }
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "title", "blocks", "freeBox"],
  title: ["title"],
  blocks: ["blocks", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicResumeHeading__ArgProps,
      internalVariantPropNames: PlasmicResumeHeading__VariantProps
    });

    return PlasmicResumeHeading__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicResumeHeading";
  } else {
    func.displayName = `PlasmicResumeHeading.${nodeName}`;
  }
  return func;
}

export const PlasmicResumeHeading = Object.assign(
  // Top-level PlasmicResumeHeading renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    title: makeNodeComponent("title"),
    blocks: makeNodeComponent("blocks"),
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicResumeHeading
    internalVariantProps: PlasmicResumeHeading__VariantProps,
    internalArgProps: PlasmicResumeHeading__ArgProps
  }
);

export default PlasmicResumeHeading;
/* prettier-ignore-end */
