// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nq12TutH13we1UigJmjqSV
// Component: K1x6xlyBVK
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: ibY8vYTLSJ-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_tag_resume.module.css"; // plasmic-import: nq12TutH13we1UigJmjqSV/projectcss
import sty from "./PlasmicResumeTagAddNew.module.css"; // plasmic-import: K1x6xlyBVK/css

export const PlasmicResumeTagAddNew__VariantProps = new Array();

export const PlasmicResumeTagAddNew__ArgProps = new Array();

function PlasmicResumeTagAddNew__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button)}
        color={"softYellow"}
      >
        {"new tag +"}
      </Button>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "button"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicResumeTagAddNew__ArgProps,
      internalVariantPropNames: PlasmicResumeTagAddNew__VariantProps
    });

    return PlasmicResumeTagAddNew__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicResumeTagAddNew";
  } else {
    func.displayName = `PlasmicResumeTagAddNew.${nodeName}`;
  }
  return func;
}

export const PlasmicResumeTagAddNew = Object.assign(
  // Top-level PlasmicResumeTagAddNew renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicResumeTagAddNew
    internalVariantProps: PlasmicResumeTagAddNew__VariantProps,
    internalArgProps: PlasmicResumeTagAddNew__ArgProps
  }
);

export default PlasmicResumeTagAddNew;
/* prettier-ignore-end */
