// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nq12TutH13we1UigJmjqSV
// Component: L_e0J81MWq
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Resume from "../../Resume"; // plasmic-import: tJhCcLyhgP/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_tag_resume.module.css"; // plasmic-import: nq12TutH13we1UigJmjqSV/projectcss
import sty from "./PlasmicEditViewFullPage.module.css"; // plasmic-import: L_e0J81MWq/css

export const PlasmicEditViewFullPage__VariantProps = new Array();

export const PlasmicEditViewFullPage__ArgProps = new Array();

function PlasmicEditViewFullPage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Resume
            data-plasmic-name={"resume"}
            data-plasmic-override={overrides.resume}
            className={classNames("__wab_instance", sty.resume)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "resume"],
  resume: ["resume"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicEditViewFullPage__ArgProps,
      internalVariantPropNames: PlasmicEditViewFullPage__VariantProps
    });

    return PlasmicEditViewFullPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEditViewFullPage";
  } else {
    func.displayName = `PlasmicEditViewFullPage.${nodeName}`;
  }
  return func;
}

export const PlasmicEditViewFullPage = Object.assign(
  // Top-level PlasmicEditViewFullPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    resume: makeNodeComponent("resume"),
    // Metadata about props expected for PlasmicEditViewFullPage
    internalVariantProps: PlasmicEditViewFullPage__VariantProps,
    internalArgProps: PlasmicEditViewFullPage__ArgProps
  }
);

export default PlasmicEditViewFullPage;
/* prettier-ignore-end */
